Algoritmo "06-exemplo_funcao_valorfixo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor    : Edson Orivaldo Lessa Junior
// Descrição    : Função sem parâmetro que retorna sempre o valor 10
// Data atual   : 30/06/2025

Var
   resultado: inteiro

funcao valorFixo(): inteiro
inicio
   retorne 10
fimfuncao

inicio
   resultado <- valorFixo()

   escreval("O valor retornado pela função é: ", resultado)
fimalgoritmo
